// Generated by CoffeeScript 1.8.0
(function() {
  var argv, banner, coffee, concat, fs, gulp, header, pkg, sourcemaps, sources, uglify, util, watch, wrap;

  pkg = require('./package.json');

  argv = require('minimist')(process.argv.slice(2));

  gulp = require('gulp');

  util = require('gulp-util');

  coffee = require('gulp-coffee');

  header = require('gulp-header');

  concat = require('gulp-concat');

  uglify = require('gulp-uglify');

  watch = require('gulp-watch');

  wrap = require('gulp-wrap');

  sourcemaps = require('gulp-sourcemaps');

  fs = require('fs');

  banner = function() {
    return ['// Uberbox.js', '// version: ' + pkg.version, '// author: ' + pkg.author, '// license: ' + pkg.licenses[0].type].join('\n') + '\n';
  };

  sources = ['uberbox', 'models', 'sliding_window_item', 'sliding_window', 'carousel', 'lightbox'].map(function(file) {
    return "src/" + file + ".coffee";
  });

  gulp.task('build', function() {
    var uberbox, uberboxMin;
    uberbox = gulp.src(sources).pipe(concat('uberbox.js')).pipe(coffee({
      bare: true
    }).on('error', util.log)).pipe(wrap({
      src: 'exports.js'
    })).pipe(header(banner())).pipe(gulp.dest('dist'));
    return uberboxMin = uberbox.pipe(concat('uberbox.min.js')).pipe(uglify()).pipe(header(banner())).pipe(gulp.dest('dist'));
  });

  gulp.task('watch', ['build'], function() {
    return gulp.watch('src/*.coffee', ['build']);
  });

}).call(this);
