// Generated by CoffeeScript 1.8.0
(function() {
  Uberbox.Utils = (function() {
    function Utils() {}

    Utils.supportsFullScreen = function() {
      var el, prefix, _i, _len, _ref;
      el = document.documentElement;
      if (el.requestFullscreen) {
        return true;
      }
      _ref = ['moz', 'webkit', 'ms'];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        prefix = _ref[_i];
        if (el["" + prefix + "RequestFullScreen"]) {
          return true;
        }
      }
      return false;
    };

    Utils.enterFullScreen = function(el) {
      var func, prefix, _i, _len, _ref, _results;
      if (!el) {
        el = document.documentElement;
      }
      if (el.requestFullscreen) {
        return element.requestFullscreen();
      } else {
        _ref = ['moz', 'webkit', 'ms'];
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          prefix = _ref[_i];
          if (func = el["" + prefix + "RequestFullScreen"]) {
            _results.push(func());
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      }
    };

    Utils.prototype.exitFullScreen = function() {
      var el, func, prefix, _i, _len, _ref, _results;
      el = document.documentElement;
      if (el.exitFullscreen) {
        return el.exitFullscreen();
      } else {
        _ref = ['moz', 'webkit', 'ms'];
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          prefix = _ref[_i];
          if (func = el["" + prefix + "ExitFullScreen"]) {
            _results.push(func());
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      }
    };

    return Utils;

  })();

}).call(this);
